#' Example local ancestry correlation: K = 6
#'
#' Data frame containing local ancestry correlation at pairs of
#' loci separated by various distances apart, for an admixed
#' population with 6 ancestral populations, 10 generations since
#' admixture, and admixture proportions contained in example_props_K6.
#' Values generated by adding noise to expected correlation,
#' and some values may lie outside (-1,1), which in practice should
#' not occur.
#'
#' @format Data frame has 3 columns named theta, corr, and anc.
#' \describe{
#'    \item{theta} recombination fraction between loci
#'    \item{corr} correlation in local ancestry at the loci
#'    \item{anc} which ancestral components are being compared (e.g., '1_1', '2_3')
#' }
#' Number of rows does not matter.
#'
#' @source Code to generate data available in data-raw.
#' @name example_corr_K6
"example_corr_K6"
